### ISSUE TITLE
Implement dynamic Player URL

### ISSUE THREAD

**Issue by chau-alexandre** [graasp/graasp-player#136]
Currently, the Player always keeps the URL of the opened item as window location. This behaviour is however often undesirable, for instance when opening a hierarchy of items: if the user scrolls the content, and then wishes to refresh the page (e.g. to update the content of a given app), the entire tree is reloaded and the viewing position resets to the top-level item (the initial URL).

We should implement a mechanism so that the window URL is dynamically updated while the user is scrolling the content. E.g. if user opens item A with URL `<host>/a` and then expands its child B, then the URL in the browser window should automatically update to `<host>/a/b` and when the user then refreshes the page, the view should still open the hierarchy at item A but already focused at child B.

This can be implemented by first improving the lazy loading mechanism (e.g. using `react-window` and the scrollToItem API), combined with URL changes (e.g. react-router? though we do not want to re-render when updating, or use a custom wrapper to the DOM API).

**Comment by pyphilia** [comment]
closed with https://github.com/graasp/graasp-player/pull/441

**Comment by pyphilia** [comment]
We added the navigation but not the update of the url.
