### ISSUE TITLE
Fix folder title running out of card

### ISSUE THREAD

**Issue by spaenleh** [graasp/graasp-player#181]
And only the title is clickable, we might want the whole card to be clickable.

**Comment by spaenleh** [comment]
Here is a example. This is a pinned folder in the player view.
The title is overflowing form the card.

<img width="558" alt="Capture d’écran 2023-02-21 à 17 04 26" src="https://user-images.githubusercontent.com/39373170/220397752-98a7618a-01db-40bb-8db7-79bea536537f.png">

We should ideally use the card component from ui.

**Comment by juancarlosfarah** [comment]
@MalinSvenberg, here's another small task to get started. Let me, @spaenleh, and/or @pyphilia know if you have any questions.

**Comment by juancarlosfarah** [comment]
@spaenleh, @pyphilia, this should be factored out to UI or is there already a card component that can be used?

**Comment by spaenleh** [comment]
I think the idea would be to use the `Card` component from `@graasp/ui` that you can [see in storybook](https://graasp.github.io/graasp-ui/?path=/story/common-card--example)
