### ISSUE TITLE
Add skeleton for navigation buttons

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-player#719]
On loading navigation buttons don't show.

On loading
![image](https://github.com/graasp/graasp-player/assets/11229627/b069b126-4606-496f-b58d-c03929ad96b4)

After loading
![image (1)](https://github.com/graasp/graasp-player/assets/11229627/d6572348-834e-42cd-a027-075007b00620)

**Comment by spaenleh** [comment]
fixed in #726
